# CUDA 11.8 on aarch needs newer glibc, which requires us to override
# the whole monster zip just to bump c_stdlib_version
c_stdlib_version:                                   # [linux and aarch64]
  - 2.17                                            # [linux and aarch64]
  - 2.28                                            # [linux and aarch64]
  - 2.17                                            # [linux and aarch64]
# rest just to make smithy happy
docker_image:                                       # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64      # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-cuda:11.8        # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64      # [linux and aarch64]
c_compiler_version:                                 # [linux and aarch64]
  - 12                                              # [linux and aarch64]
  - 11                                              # [linux and aarch64]
  - 12                                              # [linux and aarch64]
cxx_compiler_version:                               # [linux and aarch64]
  - 12                                              # [linux and aarch64]
  - 11                                              # [linux and aarch64]
  - 12                                              # [linux and aarch64]
fortran_compiler_version:                           # [linux and aarch64]
  - 12                                              # [linux and aarch64]
  - 11                                              # [linux and aarch64]
  - 12                                              # [linux and aarch64]
cdt_name:                                           # [linux and aarch64]
  - cos7                                            # [linux and aarch64]
  - cos7                                            # [linux and aarch64]
  - cos7                                            # [linux and aarch64]
cuda_compiler:                                      # [linux and aarch64]
  - None                                            # [linux and aarch64]
  - nvcc                                            # [linux and aarch64]
  - cuda-nvcc                                       # [linux and aarch64]
cuda_compiler_version:                              # [linux and aarch64]
  - None                                            # [linux and aarch64]
  - 11.8                                            # [linux and aarch64]
  - 12.0                                            # [linux and aarch64]
