{% set name = "pycuda" %}
{% set version = "2025.1.1" %}
{% set sha256 = "bab0678d43f469c865f5fe6024f481c781ec51fefe6686acd66c672bfabea34f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # symlink not implemented in pypy
  skip: true  # [win and python_impl == "pypy"]
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  # CUDA 11.8 aarch needs newer glibc, but we don't have an image for that
  skip: true  # [aarch64 and cuda_compiler_version == "11.8"]
  missing_dso_whitelist:
    - '*/libcuda.*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

  host:
    - cuda-version {{ cuda_compiler_version }}
    - python
    - pip
    - setuptools
    - libboost-python-devel
    - libboost-devel
    - numpy
    - cuda-profiler-api  # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev      # [(cuda_compiler_version or "").startswith("12")]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytools >=2011.2
    - appdirs >=1.4.0
    - mako

test:
  requires:
    - cuda-version {{ cuda_compiler_version }}
    - python
    - pytest >=2
  source_files:
    - test
  files:
    - pkg_test.py
  commands:
    - export cuda_compiler_version={{ cuda_compiler_version }}  # [unix]
    - set cuda_compiler_version={{ cuda_compiler_version }}     # [win]
    - python pkg_test.py

about:
  home: http://pypi.python.org/pypi/pycuda
  doc_url: https://documen.tician.de/pycuda
  dev_url: http://github.com/inducer/pycuda
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for CUDA
  description: |
    PyCUDA lets you access GPUs from Python, through the CUDA parallel
    compute interface.
      
extra:
  recipe-maintainers:
    - inducer
