{% set name = "pycuda" %}
{% set version = "2023.1" %}
{% set sha256 = "175ff675f0cf10e38e9adc03ed5df3ed8d8abf7da5134c8dccec752e8a0a3e91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # symlink not implemented in pypy
  skip: true  # [win and python_impl == "pypy"]
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  missing_dso_whitelist:
    - '*/libcuda.*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

  host:
    - python
    - pip
    - libboost-python-devel
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytools >=2011.2
    - appdirs >=1.4.0
    - mako

test:
  requires:
    - pytest >=2
  source_files:
    - test

about:
  home: http://pypi.python.org/pypi/pycuda
  doc_url: https://documen.tician.de/pycuda
  dev_url: http://github.com/inducer/pycuda
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for CUDA
  description: |
    PyCUDA lets you access GPUs from Python, through the CUDA parallel
    compute interface.
      
extra:
  recipe-maintainers:
    - inducer
