# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.10.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.10.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h0ddaaa3feb
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.8.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.8.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h0a220dbe6f
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.8.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_he629ea2e4b
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.9.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.9.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_hdc71300b00
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.9.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.21python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h036467f4de
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.23python3.11.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.1cxx_compiler_version10numpy1.23python3.11.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h41c3058797
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.10.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.10.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h066d212e90
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.8.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.8.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h6a63ef7825
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.8.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h67aa2865a3
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.9.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.9.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h61f9ca2711
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.9.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.21python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_hd8d8d78dbe
      ? linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.23python3.11.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10numpy1.23python3.11.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG: linux_64_c_compiler_version10cuda_c_h773d6bafa2
      ? linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.10.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.10.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_c_compiler_version12cuda_c_h3392e0deed
      ? linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.8.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.8.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_c_compiler_version12cuda_c_h44974c728d
      ? linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.8.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_c_compiler_version12cuda_c_h5b4e9920ea
      ? linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.9.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.9.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_c_compiler_version12cuda_c_h1245037ba6
      ? linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.9.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.21python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_c_compiler_version12cuda_c_h1b945241d8
      ? linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.23python3.11.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.23python3.11.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_c_compiler_version12cuda_c_h7666162fbd
      ? linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.10.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.10.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.2
        SHORT_CONFIG: linux_64_c_compiler_version7cuda_co_hcd03346298
      ? linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.8.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.8.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.2
        SHORT_CONFIG: linux_64_c_compiler_version7cuda_co_ha8376f4f94
      ? linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.8.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.2
        SHORT_CONFIG: linux_64_c_compiler_version7cuda_co_h37eabd9854
      ? linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.9.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.9.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.2
        SHORT_CONFIG: linux_64_c_compiler_version7cuda_co_haff1a83b73
      ? linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.9.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.2
        SHORT_CONFIG: linux_64_c_compiler_version7cuda_co_h88f42ed723
      ? linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.23python3.11.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7numpy1.23python3.11.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.2
        SHORT_CONFIG: linux_64_c_compiler_version7cuda_co_h87458ba4d3
      ? linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.10.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.10.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG: linux_64_c_compiler_version9cuda_co_he8689d05eb
      ? linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.8.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.8.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG: linux_64_c_compiler_version9cuda_co_hd915ce7519
      ? linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.8.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG: linux_64_c_compiler_version9cuda_co_h0d8cc5b8fb
      ? linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.9.____73_pypypython_implpypy
      : CONFIG: linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.9.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG: linux_64_c_compiler_version9cuda_co_ha0aa4828fc
      ? linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.9.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG: linux_64_c_compiler_version9cuda_co_hb1044af815
      ? linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.23python3.11.____cpythonpython_implcpython
      : CONFIG: linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.23python3.11.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG: linux_64_c_compiler_version9cuda_co_h0dfeb90da5
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        export CI=azure
        export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        export CONDA_BLD_DIR=build_artifacts
        export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
        # Archive everything in CONDA_BLD_DIR except environments
        export BLD_ARTIFACT_PREFIX=conda_artifacts
        if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
          # Archive the CONDA_BLD_DIR environments only when the job fails
          export ENV_ARTIFACT_PREFIX=conda_envs
        fi
        ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)